name: Build and Test Foody API

on:
  push:
    branches:
      - main

env:
  FOODY_USER: ${{ secrets.FOODY_USER }}
  FOODY_PASS: ${{ secrets.FOODY_PASS }}

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore Exam-Prep-BackEnd-QA.sln

      - name: Build solution
        run: msbuild Exam-Prep-BackEnd-QA.sln /p:Configuration=Release

      - name: Run tests
        run: dotnet test Exam-Prep-BackEnd-QA.sln --configuration Release --no-build